name = "gquery"
version = "0.1.0"
target = "javascript"

description = "A type-safe query/cache library for Gleam, inspired by TanStack Query"
licences = ["MIT"]

[[links]]
title = "Repository"
href = "https://github.com/andresgutgon/gleam_query"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
