name = "gleam_query"
version = "0.1.0"

# description = "A type-safe query/cache library for Gleam, inspired by TanStack Query"
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "andresgutgon", repo = "gleam_query" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
